--- @class HighlightDefinition
--- @field fg string?
--- @field bg string?
--- @field sp string?
--- @field blend integer?
--- @field bold boolean?
--- @field standout boolean?
--- @field underline boolean?
--- @field undercurl boolean?
--- @field underdouble boolean?
--- @field underdotted boolean?
--- @field strikethrough boolean?
--- @field italic boolean?
--- @field reverse boolean?
--- @field nocombine boolean?

--- @class ItalicConfig
--- @field strings boolean
--- @field comments boolean
--- @field operators boolean
--- @field folds boolean
--- @field emphasis boolean

--- @class ConquerorConfig
--- @field terminal_colors boolean?
--- @field undercurl boolean?
--- @field underline boolean?
--- @field bold boolean?
--- @field italic ItalicConfig?
--- @field strikethrough boolean?
--- @field invert_selection boolean?
--- @field invert_signs boolean?
--- @field invert_tabline boolean?
--- @field invert_intend_guides boolean?
--- @field inverse boolean?
--- @field overrides table<string, HighlightDefinition>?
--- @field palette_overrides table<string, string>?

local Conqueror = {}

Conqueror.config = {
  terminal_colors = true,
  undercurl = true,
  underline = true,
  bold = true,
  italic = {
    strings = true,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  invert_intend_guides = false,
  inverse = true,
  contrast = "",
  palette_overrides = {},
  overrides = {},
  dim_inactive = false,
  transparent_mode = false,
}

Conqueror.palette = require("conqueror.palette")

local function get_colors()
  local palette = Conqueror.palette
  local config = Conqueror.config

  for color, hex in pairs(config.palette_overrides) do
    palette[color] = hex
  end

  local color_groups = {
    bg0 = palette.dark0,
    bg1 = palette.dark1,
    bg2 = palette.dark2,
    bg3 = palette.dark3,
    bg4 = palette.dark4,
    fg0 = palette.light0,
    fg1 = palette.light1,
    fg2 = palette.light2,
    fg3 = palette.light3,
    fg4 = palette.light4,
    red = palette.bright_red,
    green = palette.bright_green,
    yellow = palette.bright_yellow,
    blue = palette.bright_blue,
    purple = palette.bright_purple,
    aqua = palette.bright_aqua,
    orange = palette.bright_orange,
    neutral_red = palette.neutral_red,
    neutral_green = palette.neutral_green,
    neutral_yellow = palette.neutral_yellow,
    neutral_blue = palette.neutral_blue,
    neutral_purple = palette.neutral_purple,
    neutral_aqua = palette.neutral_aqua,
    dark_red = palette.dark_red,
    dark_green = palette.dark_green,
    dark_aqua = palette.dark_aqua,
    gray = palette.gray,
    light_gray = palette.light_gray,
  }

  return color_groups
end

local function get_groups()
  local colors = get_colors()
  local config = Conqueror.config

  if config.terminal_colors then
    local term_colors = {
      colors.bg0,
      colors.neutral_red,
      colors.neutral_green,
      colors.neutral_yellow,
      colors.neutral_blue,
      colors.neutral_purple,
      colors.neutral_aqua,
      colors.fg4,
      colors.gray,
      colors.red,
      colors.green,
      colors.yellow,
      colors.blue,
      colors.purple,
      colors.aqua,
      colors.fg1,
    }

    for index, color in ipairs(term_colors) do
      vim.g["terminal_color_" .. index - 1] = color
    end
  end

  local groups = {
    -- definition
    ConquerorFg0 = { fg = colors.fg0 },
    ConquerorFg1 = { fg = colors.fg1 },
    ConquerorFg2 = { fg = colors.fg2 },
    ConquerorFg3 = { fg = colors.fg3 },
    ConquerorFg4 = { fg = colors.fg4 },
    ConquerorGray = { fg = colors.gray },
    ConquerorLightGray = { fg = colors.light_gray },
    ConquerorBg0 = { fg = colors.bg0 },
    ConquerorBg1 = { fg = colors.bg1 },
    ConquerorBg2 = { fg = colors.bg2 },
    ConquerorBg3 = { fg = colors.bg3 },
    ConquerorBg4 = { fg = colors.bg4 },
    ConquerorRed = { fg = colors.red },
    ConquerorRedBold = { fg = colors.red, bold = config.bold },
    ConquerorGreen = { fg = colors.green },
    ConquerorGreenBold = { fg = colors.green, bold = config.bold },
    ConquerorYellow = { fg = colors.yellow },
    ConquerorYellowBold = { fg = colors.yellow, bold = config.bold },
    ConquerorBlue = { fg = colors.blue },
    ConquerorBlueBold = { fg = colors.blue, bold = config.bold },
    ConquerorPurple = { fg = colors.purple },
    ConquerorPurpleBold = { fg = colors.purple, bold = config.bold },
    ConquerorAqua = { fg = colors.aqua },
    ConquerorNeutralAqua = { fg = colors.neutral_aqua },
    ConquerorAquaBold = { fg = colors.aqua, bold = config.bold },
    ConquerorOrange = { fg = colors.orange },
    ConquerorOrangeBold = { fg = colors.orange, bold = config.bold },
    ConquerorRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
        or { fg = colors.red, bg = colors.bg0, reverse = config.invert_signs },
    ConquerorGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
        or { fg = colors.green, bg = colors.bg0, reverse = config.invert_signs },
    ConquerorYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
        or { fg = colors.yellow, bg = colors.bg0, reverse = config.invert_signs },
    ConquerorBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
        or { fg = colors.blue, bg = colors.bg0, reverse = config.invert_signs },
    ConquerorPurpleSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
        or { fg = colors.purple, bg = colors.bg0, reverse = config.invert_signs },
    ConquerorAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
        or { fg = colors.aqua, bg = colors.bg0, reverse = config.invert_signs },
    ConquerorOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
        or { fg = colors.orange, bg = colors.bg0, reverse = config.invert_signs },
    ConquerorRedUnderline = { undercurl = config.undercurl, sp = colors.red },
    ConquerorGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
    ConquerorYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
    ConquerorBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
    ConquerorPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
    ConquerorAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
    ConquerorOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
	ConquerorOcurrenceSelection = { bg = colors.bg2 },

    --
    Normal = config.transparent_mode and { fg = colors.fg0, bg = nil } or { fg = colors.fg0, bg = colors.bg0 },
    NormalFloat = config.transparent_mode and { fg = colors.fg0, bg = nil } or { fg = colors.fg0, bg = colors.bg0 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { fg = colors.fg1, bg = colors.red, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    CursorLineNr = { fg = colors.fg0, bg = colors.bg1 },
    CursorLineBG = { bg = colors.bg1 },
    SagaVirtLine = { fg = colors.gray },
    NonText = { link = "ConquerorBg2" },
    SpecialKey = { link = "ConquerorFg4" },
    Visual = { bg = colors.bg3, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.fg0, bg = colors.bg0, reverse = config.inverse },
    IncSearch = { fg = colors.fg0, bg = colors.bg0, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { link = "ConquerorPurple" },
    Underlined = { fg = colors.blue, underline = config.underline },
    StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
    StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
    WinBar = { fg = colors.fg4, bg = nil },
    WinBarNC = { fg = colors.fg3, bg = nil },
    WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Directory = { link = "ConquerorBlueBold" },
    Title = { link = "ConquerorGreenBold" },
    ErrorMsg = { fg = colors.red, bg = colors.bg3, bold = config.bold },
    MoreMsg = { link = "ConquerorYellowBold" },
    ModeMsg = { link = "ConquerorYellowBold" },
    Question = { link = "ConquerorOrangeBold" },
    WarningMsg = { link = "ConquerorRedBold" },
    LineNr = { fg = colors.bg4 },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg0 },
    Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
    Cursor = { reverse = config.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "ConquerorFg0" },
    Comment = { fg = colors.gray, italic = config.italic.comments },
    Todo = { fg = colors.bg0, bg = colors.blue, bold = config.bold, italic = config.italic.comments },
    Done = { fg = colors.bg0, bold = config.green, italic = config.italic.comments },
    Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
    Statement = { link = "ConquerorOrange" },
    Conditional = { link = "ConquerorFg0" },
    Repeat = { link = "ConquerorFg0" },
    Label = { link = "ConquerorFg0" },
    Exception = { link = "ConquerorRed" },
    Operator = { fg = colors.fg4, italic = config.italic.operators },
    Keyword = { link = "ConquerorFg4" },
    Identifier = { link = "ConquerorFg1" },
    Function = { link = "ConquerorRedBold" },
    PreProc = { link = "ConquerorLightGray" },
    Include = { link = "ConquerorLightGray" },
    Define = { link = "ConquerorLightGray" },
    Macro = { link = "ConquerorLightGray" },
    PreCondit = { link = "ConquerorLightGray" },
    Constant = { link = "ConquerorYellow" },
    Character = { link = "ConquerorFg2" },
    String = { fg = colors.fg2, italic = config.italic.strings },
    Boolean = { link = "ConquerorAqua" },
    Number = { link = "ConquerorAqua" },
    Float = { link = "ConquerorAqua" },
    Type = { link = "ConquerorRedBold" },
    StorageClass = { link = "ConquerorOrange" },
    Structure = { link = "ConquerorRedBold" },
    Typedef = { link = "ConquerorRedBold" },
    Pmenu = { fg = colors.fg1, bg = colors.bg2 },
    PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.bg4 },
    DiffDelete = { bg = colors.dark_red },
    DiffAdd = { bg = colors.dark_green },
    DiffChange = { bg = colors.dark_aqua },
    DiffText = { bg = colors.fg4, fg = colors.fg0 },
    SpellCap = { link = "ConquerorBlueUnderline" },
    SpellBad = { link = "ConquerorRedUnderline" },
    SpellLocal = { link = "ConquerorAquaUnderline" },
    SpellRare = { link = "ConquerorPurpleUnderline" },
    Whitespace = { fg = colors.bg1 },
    Delimiter = { link = "ConquerorBg3" },
    EndOfBuffer = { link = "NonText" },
    DiagnosticError = { link = "ConquerorRed" },
    DiagnosticSignError = { link = "ConquerorRedSign" },
    DiagnosticUnderlineError = { link = "ConquerorRedUnderline" },
    DiagnosticWarn = { link = "ConquerorYellow" },
    DiagnosticSignWarn = { link = "ConquerorYellowSign" },
    DiagnosticUnderlineWarn = { link = "ConquerorYellowUnderline" },
    DiagnosticInfo = { link = "ConquerorGreen" },
    DiagnosticSignInfo = { link = "ConquerorBlueSign" },
    DiagnosticUnderlineInfo = { link = "ConquerorBlueUnderline" },
    DiagnosticHint = { link = "ConquerorAqua" },
    DiagnosticSignHint = { link = "ConquerorAquaSign" },
    DiagnosticUnderlineHint = { link = "ConquerorAquaUnderline" },
    DiagnosticFloatingError = { link = "ConquerorRed" },
    DiagnosticFloatingWarn = { link = "ConquerorOrange" },
    DiagnosticFloatingInfo = { link = "ConquerorBlue" },
    DiagnosticFloatingHint = { link = "ConquerorAqua" },
    DiagnosticVirtualTextError = { link = "ConquerorRed" },
    DiagnosticVirtualTextWarn = { link = "ConquerorYellow" },
    DiagnosticVirtualTextInfo = { link = "ConquerorBlue" },
    DiagnosticVirtualTextHint = { link = "ConquerorAqua" },
    DiagnosticOk = { link = "ConquerorGreenSign" },
    LspReferenceRead = { link = "ConquerorOcurrenceSelection" },
    LspReferenceText = { link = "ConquerorOcurrenceSelection" },
    LspReferenceWrite = { link = "ConquerorOcurrenceSelection" },
    LspCodeLens = { link = "ConquerorGray" },
    LspSignatureActiveParameter = { link = "Search" },
    gitcommitSelectedFile = { link = "ConquerorGreen" },
    gitcommitDiscardedFile = { link = "ConquerorRed" },
    GitSignsAdd = { link = "ConquerorGreen" },
    GitSignsChange = { link = "ConquerorAqua" },
    GitSignsDelete = { link = "ConquerorRed" },
    NvimTreeSymlink = { fg = colors.neutral_aqua },
    NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
    NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
    NvimTreeFileIcon = { fg = colors.light2 },
    NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
    NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
    NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
    NvimTreeImageFile = { fg = colors.neutral_purple },
    NvimTreeIndentMarker = { fg = colors.dark3 },
    NvimTreeGitDirty = { fg = colors.neutral_yellow },
    NvimTreeGitStaged = { fg = colors.neutral_yellow },
    NvimTreeGitMerge = { fg = colors.neutral_purple },
    NvimTreeGitRenamed = { fg = colors.neutral_purple },
    NvimTreeGitNew = { fg = colors.neutral_yellow },
    NvimTreeGitDeleted = { fg = colors.neutral_red },
    NvimTreeWindowPicker = { bg = colors.aqua },
    TelescopePromptCounter = { fg = colors.red },
    debugPC = { link = "DiffAdd" },
    debugBreakpoint = { link = "ConquerorRedSign" },
    StartifyBracket = { link = "ConquerorFg3" },
    StartifyFile = { link = "ConquerorFg1" },
    StartifyNumber = { link = "ConquerorBlue" },
    StartifyPath = { link = "ConquerorGray" },
    StartifySlash = { link = "ConquerorGray" },
    StartifySection = { link = "ConquerorYellow" },
    StartifySpecial = { link = "ConquerorBg2" },
    StartifyHeader = { link = "ConquerorOrange" },
    StartifyFooter = { link = "ConquerorBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    DirvishPathTail = { link = "ConquerorAqua" },
    DirvishArg = { link = "ConquerorYellow" },
    netrwDir = { link = "ConquerorAqua" },
    netrwClassify = { link = "ConquerorAqua" },
    netrwLink = { link = "ConquerorGray" },
    netrwSymLink = { link = "ConquerorFg1" },
    netrwExe = { link = "ConquerorYellow" },
    netrwComment = { link = "ConquerorGray" },
    netrwList = { link = "ConquerorBlue" },
    netrwHelpCmd = { link = "ConquerorAqua" },
    netrwCmdSep = { link = "ConquerorFg3" },
    netrwVersion = { link = "ConquerorGreen" },
    NERDTreeDir = { link = "ConquerorAqua" },
    NERDTreeDirSlash = { link = "ConquerorAqua" },
    NERDTreeOpenable = { link = "ConquerorOrange" },
    NERDTreeClosable = { link = "ConquerorOrange" },
    NERDTreeFile = { link = "ConquerorFg1" },
    NERDTreeExecFile = { link = "ConquerorYellow" },
    NERDTreeUp = { link = "ConquerorGray" },
    NERDTreeCWD = { link = "ConquerorGreen" },
    NERDTreeHelp = { link = "ConquerorFg1" },
    NERDTreeToggleOn = { link = "ConquerorGreen" },
    NERDTreeToggleOff = { link = "ConquerorRed" },
    CocErrorSign = { link = "ConquerorRedSign" },
    CocWarningSign = { link = "ConquerorOrangeSign" },
    CocInfoSign = { link = "ConquerorBlueSign" },
    CocHintSign = { link = "ConquerorAquaSign" },
    CocErrorFloat = { link = "ConquerorRed" },
    CocWarningFloat = { link = "ConquerorOrange" },
    CocInfoFloat = { link = "ConquerorBlue" },
    CocHintFloat = { link = "ConquerorAqua" },
    CocDiagnosticsError = { link = "ConquerorRed" },
    CocDiagnosticsWarning = { link = "ConquerorOrange" },
    CocDiagnosticsInfo = { link = "ConquerorBlue" },
    CocDiagnosticsHint = { link = "ConquerorAqua" },
    CocSelectedText = { link = "ConquerorRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "ConquerorGray" },
    CocErrorHighlight = { link = "ConquerorRedUnderline" },
    CocWarningHighlight = { link = "ConquerorOrangeUnderline" },
    CocInfoHighlight = { link = "ConquerorBlueUnderline" },
    CocHintHighlight = { link = "ConquerorAquaUnderline" },
    TelescopeNormal = { link = "ConquerorFg0" },
    TelescopeSelection = { fg = colors.fg1, bg = colors.bg1, bold = config.bold },
    TelescopeSelectionCaret = { link = "ConquerorRed" },
    TelescopeMultiSelection = { link = "ConquerorGray" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "ConquerorBlue" },
    TelescopePromptPrefix = { link = "ConquerorRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    CmpItemAbbr = { link = "ConquerorFg0" },
    CmpItemAbbrDeprecated = { link = "ConquerorFg1" },
    CmpItemAbbrMatch = { link = "ConquerorBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "ConquerorBlueUnderline" },
    CmpItemMenu = { link = "ConquerorGray" },
    CmpItemKindText = { link = "ConquerorOrange" },
    CmpItemKindVariable = { link = "ConquerorOrange" },
    CmpItemKindMethod = { link = "ConquerorBlue" },
    CmpItemKindFunction = { link = "ConquerorBlue" },
    CmpItemKindConstructor = { link = "ConquerorYellow" },
    CmpItemKindUnit = { link = "ConquerorBlue" },
    CmpItemKindField = { link = "ConquerorBlue" },
    CmpItemKindClass = { link = "ConquerorYellow" },
    CmpItemKindInterface = { link = "ConquerorYellow" },
    CmpItemKindModule = { link = "ConquerorBlue" },
    CmpItemKindProperty = { link = "ConquerorBlue" },
    CmpItemKindValue = { link = "ConquerorOrange" },
    CmpItemKindEnum = { link = "ConquerorYellow" },
    CmpItemKindOperator = { link = "ConquerorYellow" },
    CmpItemKindKeyword = { link = "ConquerorPurple" },
    CmpItemKindEvent = { link = "ConquerorPurple" },
    CmpItemKindReference = { link = "ConquerorPurple" },
    CmpItemKindColor = { link = "ConquerorPurple" },
    CmpItemKindSnippet = { link = "ConquerorGreen" },
    CmpItemKindFile = { link = "ConquerorBlue" },
    CmpItemKindFolder = { link = "ConquerorBlue" },
    CmpItemKindEnumMember = { link = "ConquerorAqua" },
    CmpItemKindConstant = { link = "ConquerorOrange" },
    CmpItemKindStruct = { link = "ConquerorYellow" },
    CmpItemKindTypeParameter = { link = "ConquerorYellow" },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "ConquerorOrange" },
    diffNewFile = { link = "ConquerorYellow" },
    diffOldFile = { link = "ConquerorOrange" },
    diffLine = { link = "ConquerorBlue" },
    diffIndexLine = { link = "diffChanged" },
    NavicIconsFile = { link = "ConquerorBlue" },
    NavicIconsModule = { link = "ConquerorOrange" },
    NavicIconsNamespace = { link = "ConquerorBlue" },
    NavicIconsPackage = { link = "ConquerorAqua" },
    NavicIconsClass = { link = "ConquerorYellow" },
    NavicIconsMethod = { link = "ConquerorBlue" },
    NavicIconsProperty = { link = "ConquerorAqua" },
    NavicIconsField = { link = "ConquerorPurple" },
    NavicIconsConstructor = { link = "ConquerorBlue" },
    NavicIconsEnum = { link = "ConquerorPurple" },
    NavicIconsInterface = { link = "ConquerorGreen" },
    NavicIconsFunction = { link = "ConquerorBlue" },
    NavicIconsVariable = { link = "ConquerorPurple" },
    NavicIconsConstant = { link = "ConquerorOrange" },
    NavicIconsString = { link = "ConquerorGreen" },
    NavicIconsNumber = { link = "ConquerorOrange" },
    NavicIconsBoolean = { link = "ConquerorOrange" },
    NavicIconsArray = { link = "ConquerorOrange" },
    NavicIconsObject = { link = "ConquerorOrange" },
    NavicIconsKey = { link = "ConquerorAqua" },
    NavicIconsNull = { link = "ConquerorOrange" },
    NavicIconsEnumMember = { link = "ConquerorYellow" },
    NavicIconsStruct = { link = "ConquerorPurple" },
    NavicIconsEvent = { link = "ConquerorYellow" },
    NavicIconsOperator = { link = "ConquerorRed" },
    NavicIconsTypeParameter = { link = "ConquerorRed" },
    NavicText = { link = "ConquerorWhite" },
    NavicSeparator = { link = "ConquerorWhite" },
    htmlTag = { link = "ConquerorAquaBold" },
    htmlEndTag = { link = "ConquerorAquaBold" },
    htmlTagName = { link = "ConquerorBlue" },
    htmlArg = { link = "ConquerorOrange" },
    htmlTagN = { link = "ConquerorFg1" },
    htmlSpecialTagName = { link = "ConquerorBlue" },
    htmlLink = { fg = colors.fg4, underline = config.underline },
    htmlSpecialChar = { link = "ConquerorRed" },
    htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      bold = config.bold,
      italic = true,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = true,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    xmlTag = { link = "ConquerorAquaBold" },
    xmlEndTag = { link = "ConquerorAquaBold" },
    xmlTagName = { link = "ConquerorBlue" },
    xmlEqual = { link = "ConquerorBlue" },
    docbkKeyword = { link = "ConquerorAquaBold" },
    xmlDocTypeDecl = { link = "ConquerorGray" },
    xmlDocTypeKeyword = { link = "ConquerorPurple" },
    xmlCdataStart = { link = "ConquerorGray" },
    xmlCdataCdata = { link = "ConquerorPurple" },
    dtdFunction = { link = "ConquerorGray" },
    dtdTagName = { link = "ConquerorPurple" },
    xmlAttrib = { link = "ConquerorOrange" },
    xmlProcessingDelim = { link = "ConquerorGray" },
    dtdParamEntityPunct = { link = "ConquerorGray" },
    dtdParamEntityDPunct = { link = "ConquerorGray" },
    xmlAttribPunct = { link = "ConquerorGray" },
    xmlEntity = { link = "ConquerorRed" },
    xmlEntityPunct = { link = "ConquerorRed" },
    clojureKeyword = { link = "ConquerorBlue" },
    clojureCond = { link = "ConquerorOrange" },
    clojureSpecial = { link = "ConquerorOrange" },
    clojureDefine = { link = "ConquerorOrange" },
    clojureFunc = { link = "ConquerorYellow" },
    clojureRepeat = { link = "ConquerorYellow" },
    clojureCharacter = { link = "ConquerorAqua" },
    clojureStringEscape = { link = "ConquerorAqua" },
    clojureException = { link = "ConquerorRed" },
    clojureRegexp = { link = "ConquerorAqua" },
    clojureRegexpEscape = { link = "ConquerorAqua" },
    clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "ConquerorFg3" },
    clojureAnonArg = { link = "ConquerorYellow" },
    clojureVariable = { link = "ConquerorBlue" },
    clojureMacro = { link = "ConquerorOrange" },
    clojureMeta = { link = "ConquerorYellow" },
    clojureDeref = { link = "ConquerorYellow" },
    clojureQuote = { link = "ConquerorYellow" },
    clojureUnquote = { link = "ConquerorYellow" },
    cOperator = { link = "ConquerorPurple" },
    cppOperator = { link = "ConquerorPurple" },
    cStructure = { link = "ConquerorOrange" },
    pythonBuiltin = { link = "ConquerorOrange" },
    pythonBuiltinObj = { link = "ConquerorOrange" },
    pythonBuiltinFunc = { link = "ConquerorOrange" },
    pythonFunction = { link = "ConquerorAqua" },
    pythonDecorator = { link = "ConquerorRed" },
    pythonInclude = { link = "ConquerorBlue" },
    pythonImport = { link = "ConquerorBlue" },
    pythonRun = { link = "ConquerorBlue" },
    pythonCoding = { link = "ConquerorBlue" },
    pythonOperator = { link = "ConquerorRed" },
    pythonException = { link = "ConquerorRed" },
    pythonExceptions = { link = "ConquerorPurple" },
    pythonBoolean = { link = "ConquerorPurple" },
    pythonDot = { link = "ConquerorFg3" },
    pythonConditional = { link = "ConquerorRed" },
    pythonRepeat = { link = "ConquerorRed" },
    pythonDottedName = { link = "ConquerorGreenBold" },
    cssBraces = { link = "ConquerorBlue" },
    cssFunctionName = { link = "ConquerorYellow" },
    cssIdentifier = { link = "ConquerorOrange" },
    cssClassName = { link = "ConquerorGreen" },
    cssColor = { link = "ConquerorBlue" },
    cssSelectorOp = { link = "ConquerorBlue" },
    cssSelectorOp2 = { link = "ConquerorBlue" },
    cssImportant = { link = "ConquerorGreen" },
    cssVendor = { link = "ConquerorFg1" },
    cssTextProp = { link = "ConquerorAqua" },
    cssAnimationProp = { link = "ConquerorAqua" },
    cssUIProp = { link = "ConquerorYellow" },
    cssTransformProp = { link = "ConquerorAqua" },
    cssTransitionProp = { link = "ConquerorAqua" },
    cssPrintProp = { link = "ConquerorAqua" },
    cssPositioningProp = { link = "ConquerorYellow" },
    cssBoxProp = { link = "ConquerorAqua" },
    cssFontDescriptorProp = { link = "ConquerorAqua" },
    cssFlexibleBoxProp = { link = "ConquerorAqua" },
    cssBorderOutlineProp = { link = "ConquerorAqua" },
    cssBackgroundProp = { link = "ConquerorAqua" },
    cssMarginProp = { link = "ConquerorAqua" },
    cssListProp = { link = "ConquerorAqua" },
    cssTableProp = { link = "ConquerorAqua" },
    cssFontProp = { link = "ConquerorAqua" },
    cssPaddingProp = { link = "ConquerorAqua" },
    cssDimensionProp = { link = "ConquerorAqua" },
    cssRenderProp = { link = "ConquerorAqua" },
    cssColorProp = { link = "ConquerorAqua" },
    cssGeneratedContentProp = { link = "ConquerorAqua" },
    javaScriptBraces = { link = "ConquerorFg1" },
    javaScriptFunction = { link = "ConquerorAqua" },
    javaScriptIdentifier = { link = "ConquerorRed" },
    javaScriptMember = { link = "ConquerorBlue" },
    javaScriptNumber = { link = "ConquerorPurple" },
    javaScriptNull = { link = "ConquerorPurple" },
    javaScriptParens = { link = "ConquerorFg3" },
    typescriptReserved = { link = "ConquerorAqua" },
    typescriptLabel = { link = "ConquerorAqua" },
    typescriptFuncKeyword = { link = "ConquerorAqua" },
    typescriptIdentifier = { link = "ConquerorOrange" },
    typescriptBraces = { link = "ConquerorFg1" },
    typescriptEndColons = { link = "ConquerorFg1" },
    typescriptDOMObjects = { link = "ConquerorFg1" },
    typescriptAjaxMethods = { link = "ConquerorFg1" },
    typescriptLogicSymbols = { link = "ConquerorFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "ConquerorFg1" },
    typescriptParens = { link = "ConquerorFg3" },
    typescriptOpSymbols = { link = "ConquerorFg3" },
    typescriptHtmlElemProperties = { link = "ConquerorFg1" },
    typescriptNull = { link = "ConquerorPurple" },
    typescriptInterpolationDelimiter = { link = "ConquerorAqua" },
    purescriptModuleKeyword = { link = "ConquerorAqua" },
    purescriptModuleName = { link = "ConquerorFg1" },
    purescriptWhere = { link = "ConquerorAqua" },
    purescriptDelimiter = { link = "ConquerorFg4" },
    purescriptType = { link = "ConquerorFg1" },
    purescriptImportKeyword = { link = "ConquerorAqua" },
    purescriptHidingKeyword = { link = "ConquerorAqua" },
    purescriptAsKeyword = { link = "ConquerorAqua" },
    purescriptStructure = { link = "ConquerorAqua" },
    purescriptOperator = { link = "ConquerorBlue" },
    purescriptTypeVar = { link = "ConquerorFg1" },
    purescriptConstructor = { link = "ConquerorFg1" },
    purescriptFunction = { link = "ConquerorFg1" },
    purescriptConditional = { link = "ConquerorOrange" },
    purescriptBacktick = { link = "ConquerorOrange" },
    coffeeExtendedOp = { link = "ConquerorFg3" },
    coffeeSpecialOp = { link = "ConquerorFg3" },
    coffeeCurly = { link = "ConquerorOrange" },
    coffeeParen = { link = "ConquerorFg3" },
    coffeeBracket = { link = "ConquerorOrange" },
    rubyStringDelimiter = { link = "ConquerorGreen" },
    rubyInterpolationDelimiter = { link = "ConquerorAqua" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    objcTypeModifier = { link = "ConquerorRed" },
    objcDirective = { link = "ConquerorBlue" },
    goDirective = { link = "ConquerorAqua" },
    goConstants = { link = "ConquerorPurple" },
    goDeclaration = { link = "ConquerorRed" },
    goDeclType = { link = "ConquerorBlue" },
    goBuiltins = { link = "ConquerorOrange" },
    luaIn = { link = "ConquerorRed" },
    luaFunction = { link = "ConquerorAqua" },
    luaTable = { link = "ConquerorOrange" },
    moonSpecialOp = { link = "ConquerorFg3" },
    moonExtendedOp = { link = "ConquerorFg3" },
    moonFunction = { link = "ConquerorFg3" },
    moonObject = { link = "ConquerorYellow" },
    javaAnnotation = { link = "ConquerorBlue" },
    javaDocTags = { link = "ConquerorAqua" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "ConquerorFg3" },
    javaParen1 = { link = "ConquerorFg3" },
    javaParen2 = { link = "ConquerorFg3" },
    javaParen3 = { link = "ConquerorFg3" },
    javaParen4 = { link = "ConquerorFg3" },
    javaParen5 = { link = "ConquerorFg3" },
    javaOperator = { link = "ConquerorOrange" },
    javaVarArg = { link = "ConquerorGreen" },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "ConquerorGreen" },
    elixirInterpolationDelimiter = { link = "ConquerorAqua" },
    elixirModuleDeclaration = { link = "ConquerorYellow" },
    scalaNameDefinition = { link = "ConquerorFg1" },
    scalaCaseFollowing = { link = "ConquerorFg1" },
    scalaCapitalWord = { link = "ConquerorFg1" },
    scalaTypeExtension = { link = "ConquerorFg1" },
    scalaKeyword = { link = "ConquerorRed" },
    scalaKeywordModifier = { link = "ConquerorRed" },
    scalaSpecial = { link = "ConquerorAqua" },
    scalaOperator = { link = "ConquerorFg1" },
    scalaTypeDeclaration = { link = "ConquerorYellow" },
    scalaTypeTypePostDeclaration = { link = "ConquerorYellow" },
    scalaInstanceDeclaration = { link = "ConquerorFg1" },
    scalaInterpolation = { link = "ConquerorAqua" },
    markdownItalic = { fg = colors.fg3, italic = true },
    markdownBold = { fg = colors.fg3, bold = config.bold },
    markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
    markdownH1 = { link = "ConquerorGreenBold" },
    markdownH2 = { link = "ConquerorGreenBold" },
    markdownH3 = { link = "ConquerorYellowBold" },
    markdownH4 = { link = "ConquerorYellowBold" },
    markdownH5 = { link = "ConquerorYellow" },
    markdownH6 = { link = "ConquerorYellow" },
    markdownCode = { link = "ConquerorAqua" },
    markdownCodeBlock = { link = "ConquerorAqua" },
    markdownCodeDelimiter = { link = "ConquerorAqua" },
    markdownBlockquote = { link = "ConquerorGray" },
    markdownListMarker = { link = "ConquerorGray" },
    markdownOrderedListMarker = { link = "ConquerorGray" },
    markdownRule = { link = "ConquerorGray" },
    markdownHeadingRule = { link = "ConquerorGray" },
    markdownUrlDelimiter = { link = "ConquerorFg3" },
    markdownLinkDelimiter = { link = "ConquerorFg3" },
    markdownLinkTextDelimiter = { link = "ConquerorFg3" },
    markdownHeadingDelimiter = { link = "ConquerorOrange" },
    markdownUrl = { link = "ConquerorPurple" },
    markdownUrlTitleDelimiter = { link = "ConquerorGreen" },
    markdownLinkText = { fg = colors.gray, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { link = "ConquerorBlue" },
    haskellIdentifier = { link = "ConquerorAqua" },
    haskellSeparator = { link = "ConquerorFg4" },
    haskellDelimiter = { link = "ConquerorOrange" },
    haskellOperators = { link = "ConquerorPurple" },
    haskellBacktick = { link = "ConquerorOrange" },
    haskellStatement = { link = "ConquerorPurple" },
    haskellConditional = { link = "ConquerorPurple" },
    haskellLet = { link = "ConquerorRed" },
    haskellDefault = { link = "ConquerorRed" },
    haskellWhere = { link = "ConquerorRed" },
    haskellBottom = { link = "ConquerorRedBold" },
    haskellImportKeywords = { link = "ConquerorPurpleBold" },
    haskellDeclKeyword = { link = "ConquerorOrange" },
    haskellDecl = { link = "ConquerorOrange" },
    haskellDeriving = { link = "ConquerorPurple" },
    haskellAssocType = { link = "ConquerorAqua" },
    haskellNumber = { link = "ConquerorAqua" },
    haskellPragma = { link = "ConquerorRedBold" },
    haskellTH = { link = "ConquerorAquaBold" },
    haskellForeignKeywords = { link = "ConquerorGreen" },
    haskellKeyword = { link = "ConquerorRed" },
    haskellFloat = { link = "ConquerorAqua" },
    haskellInfix = { link = "ConquerorPurple" },
    haskellQuote = { link = "ConquerorGreenBold" },
    haskellShebang = { link = "ConquerorYellowBold" },
    haskellLiquid = { link = "ConquerorPurpleBold" },
    haskellQuasiQuoted = { link = "ConquerorBlueBold" },
    haskellRecursiveDo = { link = "ConquerorPurple" },
    haskellQuotedType = { link = "ConquerorRed" },
    haskellPreProc = { link = "ConquerorFg4" },
    haskellTypeRoles = { link = "ConquerorRedBold" },
    haskellTypeForall = { link = "ConquerorRed" },
    haskellPatternKeyword = { link = "ConquerorBlue" },
    jsonKeyword = { link = "ConquerorGreen" },
    jsonQuote = { link = "ConquerorGreen" },
    jsonBraces = { link = "ConquerorFg1" },
    jsonString = { link = "ConquerorFg1" },
    mailQuoted1 = { link = "ConquerorAqua" },
    mailQuoted2 = { link = "ConquerorPurple" },
    mailQuoted3 = { link = "ConquerorYellow" },
    mailQuoted4 = { link = "ConquerorGreen" },
    mailQuoted5 = { link = "ConquerorRed" },
    mailQuoted6 = { link = "ConquerorOrange" },
    mailSignature = { link = "Comment" },
    csBraces = { link = "ConquerorFg1" },
    csEndColon = { link = "ConquerorFg1" },
    csLogicSymbols = { link = "ConquerorFg1" },
    csParens = { link = "ConquerorFg3" },
    csOpSymbols = { link = "ConquerorFg3" },
    csInterpolationDelimiter = { link = "ConquerorFg3" },
    csInterpolationAlignDel = { link = "ConquerorAquaBold" },
    csInterpolationFormat = { link = "ConquerorAqua" },
    csInterpolationFormatDel = { link = "ConquerorAquaBold" },
    rustSigil = { link = "ConquerorOrange" },
    rustEscape = { link = "ConquerorAqua" },
    rustStringContinuation = { link = "ConquerorAqua" },
    rustEnum = { link = "ConquerorAqua" },
    rustStructure = { link = "ConquerorAqua" },
    rustModPathSep = { link = "ConquerorFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "ConquerorAqua" },
    ocamlOperator = { link = "ConquerorFg1" },
    ocamlKeyChar = { link = "ConquerorOrange" },
    ocamlArrow = { link = "ConquerorOrange" },
    ocamlInfixOpKeyword = { link = "ConquerorRed" },
    ocamlConstructor = { link = "ConquerorOrange" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "ConquerorFg1" },
    LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
    LspSagaLspFinderBorder = { link = "ConquerorFg1" },
    LspSagaAutoPreview = { link = "ConquerorOrange" },
    TargetWord = { fg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "ConquerorAqua" },
    FidgetTask = { fg = colors.gray },
    LspSagaDefPreviewBorder = { link = "ConquerorBlue" },
    LspSagaHoverBorder = { link = "ConquerorOrange" },
    LspSagaRenameBorder = { link = "ConquerorBlue" },
    LspSagaDiagnosticSource = { link = "ConquerorOrange" },
    LspSagaDiagnosticBorder = { link = "ConquerorPurple" },
    LspSagaDiagnosticHeader = { link = "ConquerorGreen" },
    LspSagaSignatureHelpBorder = { link = "ConquerorGreen" },
    SagaShadow = { link = "ConquerorBg0" },
    DashboardShortCut = { link = "ConquerorOrange" },
    DashboardHeader = { link = "ConquerorAqua" },
    DashboardCenter = { link = "ConquerorYellow" },
    DashboardFooter = { fg = colors.purple, italic = true },
    MasonHighlight = { link = "ConquerorAqua" },
    MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
    MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
    MasonHighlightSecondary = { fg = colors.yellow },
    MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
    MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = colors.fg4 },
    MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
    MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
    LspInlayHint = { link = "comment" },
    CarbonFile = { link = "ConquerorFg1" },
    CarbonExe = { link = "ConquerorYellow" },
    CarbonSymlink = { link = "ConquerorAqua" },
    CarbonBrokenSymlink = { link = "ConquerorRed" },
    CarbonIndicator = { link = "ConquerorGray" },
    CarbonDanger = { link = "ConquerorRed" },
    CarbonPending = { link = "ConquerorYellow" },
    NoiceCursor = { link = "TermCursor" },
    NotifyDEBUGBorder = { link = "ConquerorBlue" },
    NotifyDEBUGIcon = { link = "ConquerorBlue" },
    NotifyDEBUGTitle = { link = "ConquerorBlue" },
    NotifyERRORBorder = { link = "ConquerorRed" },
    NotifyERRORIcon = { link = "ConquerorRed" },
    NotifyERRORTitle = { link = "ConquerorRed" },
    NotifyINFOBorder = { link = "ConquerorAqua" },
    NotifyINFOIcon = { link = "ConquerorAqua" },
    NotifyINFOTitle = { link = "ConquerorAqua" },
    NotifyTRACEBorder = { link = "ConquerorGreen" },
    NotifyTRACEIcon = { link = "ConquerorGreen" },
    NotifyTRACETitle = { link = "ConquerorGreen" },
    NotifyWARNBorder = { link = "ConquerorYellow" },
    NotifyWARNIcon = { link = "ConquerorYellow" },
    NotifyWARNTitle = { link = "ConquerorYellow" },
    GitSignsCurrentLineBlame = { fg = colors.gray },
    -- IlluminatedWordText = { link = "LspReferenceText" },
    -- IlluminatedWordRead = { link = "LspReferenceRead" },
    -- IlluminatedWordWrite = { link = "LspReferenceWrite" },
    TSRainbowRed = { fg = colors.red },
    TSRainbowOrange = { fg = colors.orange },
    TSRainbowYellow = { fg = colors.yellow },
    TSRainbowGreen = { fg = colors.green },
    TSRainbowBlue = { fg = colors.blue },
    TSRainbowViolet = { fg = colors.purple },
    TSRainbowCyan = { fg = colors.cyan },
    RainbowDelimiterRed = { fg = colors.red },
    RainbowDelimiterOrange = { fg = colors.purple },
    RainbowDelimiterYellow = { fg = colors.aqua },
    RainbowDelimiterGreen = { fg = colors.fg2 },
    RainbowDelimiterBlue = { fg = colors.green },
    RainbowDelimiterViolet = { fg = colors.orange },
    RainbowDelimiterCyan = { fg = colors.fg0 },
    DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
    DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
    DapUIBreakpointsCurrentLine = { link = "ConquerorYellow" },
    DapUIBreakpointsDisabledLine = { link = "ConquerorGray" },
    DapUIBreakpointsInfo = { link = "ConquerorAqua" },
    DapUIBreakpointsLine = { link = "ConquerorYellow" },
    DapUIBreakpointsPath = { link = "ConquerorBlue" },
    DapUICurrentFrameName = { link = "ConquerorPurple" },
    DapUIDecoration = { link = "ConquerorPurple" },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatBorder = { link = "ConquerorAqua" },
    DapUILineNumber = { link = "ConquerorYellow" },
    DapUIModifiedValue = { link = "ConquerorRed" },
    DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
    DapUIRestart = { fg = colors.green, bg = colors.bg1 },
    DapUIScope = { link = "ConquerorBlue" },
    DapUISource = { link = "ConquerorFg1" },
    DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
    DapUIStop = { fg = colors.red, bg = colors.bg1 },
    TreesitterContext = { bg = colors.bg1 },
    DapUIStoppedThread = { link = "ConquerorBlue" },
    DapUIThread = { link = "ConquerorBlue" },
    DapUIType = { link = "ConquerorOrange" },
    DapUIUnavailable = { link = "ConquerorGray" },
    DapUIWatchesEmpty = { link = "ConquerorGray" },
    DapUIWatchesError = { link = "ConquerorRed" },
    DapUIWatchesValue = { link = "ConquerorYellow" },
    DapUIWinSelect = { link = "ConquerorYellow" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    DiffviewStatusModified = { link = "ConquerorGreenBold" },
    DiffviewFilePanelInsertions = { link = "ConquerorGreenBold" },
    DiffviewFilePanelDeletions = { link = "ConquerorRedBold" },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "ConquerorRed" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "ConquerorFg1" },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.member"] = { link = "Identifier" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@markup"] = { link = "ConquerorFg1" },
    ["@markup.strong"] = { bold = config.bold },
    ["@markup.italic"] = { link = "@text.emphasis" },
    ["@markup.underline"] = { underline = config.underline },
    ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.math"] = { link = "Special" },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.list"] = { link = "Delimiter" },
    ["@markup.list.checked"] = { link = "ConquerorGreen" },
    ["@markup.list.unchecked"] = { link = "ConquerorGray" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { link = "SpecialComment" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },
    ["@module"] = { link = "ConquerorFg1" },
    ["@namespace"] = { link = "ConquerorFg1" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "ConquerorFg1" },
    ["@text.strong"] = { bold = config.bold },
    ["@text.emphasis"] = { italic = config.italic.emphasis },
    ["@text.underline"] = { underline = config.underline },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "ConquerorGreen" },
    ["@text.todo.unchecked"] = { link = "ConquerorGray" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
  }

  for g, hl in pairs(config.overrides) do
    if groups[g] then
      groups[g].link = nil
    end

    groups[g] = vim.tbl_extend("force", groups[g] or {}, hl)
  end

  return groups
end

--- @param config ConquerorConfig?
Conqueror.setup = function(config)
  Conqueror.config = vim.tbl_extend("force", Conqueror.config, config or {})
end

-- load function
Conqueror.load = function()
  if vim.version().minor < 8 then
    vim.notify_once("conqueror.nvim: nvim 0.8 or higher is needed")
    return
  end

  -- reset colors
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end

  vim.g.colors_name = "conqueror"
  vim.o.termguicolors = true

  local groups = get_groups()

  -- add highlights
  for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
  end
end

return Conqueror
